import { ComponentMeta, ComponentStory } from '@storybook/react'

import { AutoCompleteForm } from '../../components/forms'

export default {
  title: 'UI-KIT/Forms/AutoCompleteForm',
  component: AutoCompleteForm,
} as ComponentMeta<typeof AutoCompleteForm>

const Template: ComponentStory<typeof AutoCompleteForm> = (args) => (
  <AutoCompleteForm {...args} />
)
export const Primary = Template.bind({})

Primary.args = {
  onSubmit: (data) => console.log(data),
  dataFields: {
    id: 'bf9nl5nNCd',
    title: 'Регистрация образовательной организации',
    description: 'Форма создания образовательной организации',
    fields: [
      {
        id: 'HcAHt551fN',
        title: 'Данные образовательной огранизации.',
        inputs: [
          {
            id: '5EW4dwaLaO',
            required: true,
            name: 'Логотип',
            type: 'file_input',
            placeholder: 'Логотип образовательной организации',
            readonly: false,
            constraintLength: 512,
            constraintRegex: '/[*]/',
            backendName: 'logo',
            wrappedName: '',
            selectFields: [],
          },
          {
            id: 'png5yYKNNO',
            required: true,
            name: 'Договор',
            type: 'text_input',
            placeholder: 'Договор:',
            readonly: false,
            constraintLength: 100,
            constraintRegex: '/[a-zA-Zа-яА-Я0-9-.]/',
            backendName: 'contract_number',
            wrappedName: '',
            selectFields: [],
          },
          {
            id: 'OZCZbodcwc',
            required: true,
            name: 'Лицензия',
            type: 'text_input',
            placeholder: 'Номер основной лицензии:',
            readonly: false,
            constraintLength: 500,
            constraintRegex: '/[a-zA-Z0-9]/',
            backendName: 'license_number',
            wrappedName: '',
            selectFields: [],
          },
          {
            id: 'vdN4SA3mM8',
            required: true,
            name: 'Количество лицензий',
            type: 'number_input',
            placeholder: 'Количество активных лицензий:',
            readonly: false,
            constraintLength: 10,
            constraintRegex: '/[0-9]/',
            backendName: 'license_count',
            wrappedName: '',
            selectFields: [],
          },
          {
            id: 'WWau9qxsEv',
            required: true,
            name: 'Город',
            type: 'text_input',
            placeholder: 'Населенный пункт:',
            readonly: false,
            constraintLength: 150,
            constraintRegex: '/[a-zA-Zа-яА-Я0-9-.]/',
            backendName: 'city',
            wrappedName: '',
            selectFields: [],
          },
          {
            id: 'zKXIGFSqMT',
            required: true,
            name: 'Тип образовательной организации',
            type: 'select',
            placeholder: 'Тип:',
            readonly: false,
            constraintLength: 100,
            constraintRegex: '/[a-zA-Zа-яА-Я0-9-.]/',
            backendName: 'type',
            wrappedName: '',
            selectFields: [
              {
                value: 'Дошкольное образование',
                label: 'PRESCHOOL',
              },
              {
                value: 'Общее образование',
                label: 'GENERAL',
              },
              {
                value: 'Среднее спец. образование (СПО)',
                label: 'SPECIAL',
              },
              {
                value: 'Коммерческая организация',
                label: 'COMMERCIAL',
              },
              {
                value: 'Физлицо',
                label: 'PERSON',
              },
              {
                value: 'Другое',
                label: 'OTHER',
              },
            ],
          },
          {
            id: 'GrskDjtCPb',
            required: true,
            name: 'Название образовательной организации',
            type: 'text_input',
            placeholder: 'Название:',
            readonly: false,
            constraintLength: 100,
            constraintRegex: '/[a-zA-Zа-яА-Я0-9-.]/',
            backendName: 'name',
            wrappedName: '',
            selectFields: [],
          },
          {
            id: 'dEOllhD8cK',
            required: true,
            name: 'Количество пользователей',
            type: 'number_input',
            placeholder: 'Количество пользователей:',
            readonly: false,
            constraintLength: 10,
            constraintRegex: '/[0-9]/',
            backendName: 'count_users',
            wrappedName: '',
            selectFields: [],
          },
        ],
      },
      {
        id: 'KNpZJATwFz',
        title: 'Данные сотрудника.',
        inputs: [
          {
            id: 'OIGTyTUAIE',
            required: true,
            name: 'Фамилия',
            type: 'text_input',
            placeholder: 'Фамилия',
            readonly: false,
            constraintLength: 150,
            constraintRegex: '/[a-zA-Zа-яА-Я-]/',
            backendName: 'last_name',
            wrappedName: 'administration',
            selectFields: [],
          },
          {
            id: 'TC8qJW1V3m',
            required: true,
            name: 'Имя',
            type: 'text_input',
            placeholder: 'Имя',
            readonly: false,
            constraintLength: 150,
            constraintRegex: '/[a-zA-Zа-яА-Я-]/',
            backendName: 'first_name',
            wrappedName: 'administration',
            selectFields: [],
          },
          {
            id: 'exgi9mOeRT',
            required: true,
            name: 'Отчество',
            type: 'text_input',
            placeholder: 'Отчество',
            readonly: false,
            constraintLength: 150,
            constraintRegex: '/[a-zA-Zа-яА-Я-]/',
            backendName: 'middle_name',
            wrappedName: 'administration',
            selectFields: [],
          },
          {
            id: 'hcmBR3A5Yq',
            required: true,
            name: 'Должность',
            type: 'text_input',
            placeholder: 'Должность:',
            readonly: false,
            constraintLength: 200,
            constraintRegex: '/[a-zA-Zа-яА-Я0-9-./]/',
            backendName: 'position',
            wrappedName: 'administration',
            selectFields: [],
          },
          {
            id: 'dNUUsG4vUt',
            required: true,
            name: 'Телефон',
            type: 'masked_input_phone',
            placeholder: 'Телефон: (___) ___-__-__',
            readonly: false,
            constraintLength: 10,
            constraintRegex: '/[0-9]/',
            backendName: 'phone',
            wrappedName: 'administration',
            selectFields: [],
          },
          {
            id: 'YFtffEVsmV',
            required: true,
            name: 'Email',
            type: 'masked_input_email',
            placeholder: 'E-mail:',
            readonly: false,
            constraintLength: 100,
            constraintRegex: '/[a-zA-Zа-яА-Я0-9-.@]/',
            backendName: 'email',
            wrappedName: 'administration',
            selectFields: [],
          },
        ],
      },
    ],
  },
}
